# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:25:57+00:00

from __future__ import annotations

from pydantic import BaseModel

from . import DefsOkFalse, DefsOkTrue


class TestGetResponse(BaseModel):
    ok: DefsOkTrue


class TestGetResponseModel(BaseModel):
    error: str
    ok: DefsOkFalse
