# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:25:57+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AnyUrl, BaseModel, ConfigDict, Field

from . import DefsAppId, DefsBotId, DefsOkFalse, DefsOkTrue, DefsUserId


class Icons(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    image_36: AnyUrl
    image_48: AnyUrl
    image_72: AnyUrl


class Bot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    app_id: DefsAppId
    deleted: bool
    icons: Icons
    id: DefsBotId
    name: str
    updated: int
    user_id: Optional[DefsUserId] = None


class InfoGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    bot: Bot
    ok: DefsOkTrue


class Error(Enum):
    bot_not_found = 'bot_not_found'
    not_authed = 'not_authed'
    invalid_auth = 'invalid_auth'
    account_inactive = 'account_inactive'
    token_revoked = 'token_revoked'
    no_permission = 'no_permission'
    org_login_required = 'org_login_required'
    invalid_arg_name = 'invalid_arg_name'
    invalid_array_arg = 'invalid_array_arg'
    invalid_charset = 'invalid_charset'
    invalid_form_data = 'invalid_form_data'
    invalid_post_type = 'invalid_post_type'
    missing_post_type = 'missing_post_type'
    team_added_to_org = 'team_added_to_org'
    invalid_json = 'invalid_json'
    json_not_object = 'json_not_object'
    request_timeout = 'request_timeout'
    upgrade_required = 'upgrade_required'
    fatal_error = 'fatal_error'


class InfoGetResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    callstack: Optional[str] = Field(
        None, description='Note: PHP callstack is only visible in dev/qa'
    )
    error: Error
    ok: DefsOkFalse
