# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:25:57+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import DefsOkFalse, DefsOkTrue


class OpenGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkTrue


class OpenGetResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkFalse


class PublishGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkTrue


class PublishGetResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkFalse


class PushGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkTrue


class PushGetResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkFalse


class UpdateGetResponse(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkTrue


class UpdateGetResponseModel(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    ok: DefsOkFalse
